#! /bin/bash
#
# Copyright 2009 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).
#
# Check each of the branches in $LP_PROJECT_PATH and show which of them have
# uncommitted changes, also check which ones have revisions that have not yet
# landed on trunk.

source "$HOME/.rocketfuel-env.sh"
if [ "$?" != 0 ]; then
    echo "Please run rocketfuel-setup first."
    exit 1
fi

cd $LP_PROJECT_PATH
for branch in *; do
  if [ ${branch} != "$LP_TRUNK_NAME" ] && test -d ${branch} ; then
    echo "Examining ${branch}"
    cd ${branch}
    bzr status --short
    cd $LP_TRUNK_PATH
    bzr missing --theirs-only --line ../${branch} | grep -v "^You are missing"
    cd ..
  fi;
done;
